# docker-compose.dev.yml (for development)
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: fluxgym-dev
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./dev.db
      - FLUXGYM_PATH=/app/fluxgym
      - STORAGE_PATH=/app/storage
      - CUDA_VISIBLE_DEVICES=0
      - DEBUG=1
    volumes:
      - .:/app
      - ./storage:/app/storage
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
    command: ["python3", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
