
# config/models.yaml
# Supported base models for training
models:
  flux-dev:
    repo: "cocktailpeanut/xulf-dev"
    base: "black-forest-labs/FLUX.1-dev"
    license: "other"
    license_name: "flux-1-dev-non-commercial-license"
    license_link: "https://huggingface.co/black-forest-labs/FLUX.1-dev/blob/main/LICENSE.md"
    file: "flux1-dev.sft"
    recommended: true
    description: "High-quality model, best for most use cases"
    min_vram_gb: 12
    recommended_vram_gb: 16
    
  flux-schnell:
    repo: "black-forest-labs/FLUX.1-schnell"
    base: "black-forest-labs/FLUX.1-schnell"
    license: "apache-2.0"
    file: "flux1-schnell.safetensors"
    recommended: false
    description: "Faster training but lower quality results"
    min_vram_gb: 8
    recommended_vram_gb: 12
    
  flux-dev2pro:
    repo: "bdsqlsz/flux1-dev2pro-single"
    base: "black-forest-labs/FLUX.1-dev"
    license: "other"
    license_name: "flux-1-dev-non-commercial-license"
    license_link: "https://huggingface.co/black-forest-labs/FLUX.1-dev/blob/main/LICENSE.md"
    file: "flux1-dev2pro.safetensors"
    recommended: false
    description: "Enhanced version of flux-dev for better results"
    min_vram_gb: 16
    recommended_vram_gb: 20

# Model download configuration
download:
  timeout_seconds: 3600
  retry_attempts: 3
  chunk_size_mb: 50
  verify_checksums: true
  
# Automatic model management
auto_download:
  enabled: true
  on_first_use: true
  cleanup_unused: false
  cache_duration_days: 30